name: school_konnect 
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  shared_preferences: ^2.3.2
  payu_checkoutpro_flutter: ^1.4.2
  http: ^1.6.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/dav-logo.png"
  adaptive_icon_foreground: "assets/images/dav-logo.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21